services:
  database:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # backend:
  #   container_name: api
  #   build: ./backend/
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - database
  #   restart:
  #     always

volumes:
  mysql_data:
